In [ ]:
from dataclasses import dataclass

@dataclass
class Employee:
	employeeID: int
	name: str
	designation: str

	def display_details(self):
		print("Employee name is (name) : (EmpolyeeID) with designation - (designation)".
		format(name = self.name, employeeID = self.employeeID, designation = self.designation) )

Employee1 = Employee(12345, "Bradly Alicea", "Software Dev")
print(Employee1)
Employee1.display_details()

Employee(employeeID=12345, name='Bradly Alicea', designation='Software Dev')
Employee name is (name) : (EmpolyeeID) with designation - (designation)